APP:
  NAME: gin_weibo
  RUNMODE: debug # 模式: debug, release, test
  Addr: :8888 # 端口
  URL: http://localhost:8888
  KEY: base64:O+VQ74YEigLPDzLKnh2HW/yjCdU2ON9v7xuKBgSOEAo=
  ENABLE_CSRF: true # 是否开启 csrf

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: gin_weibo
  USERNAME: wutong
  PASSWORD: secret

MAIL:
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME:
  MAIL_PASSWORD:
  MAIL_ENCRYPTION:
  MAIN_FROM_ADDRESS:
