basePath: /api
definitions:
  context.CommonResponse:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  context.TokenResp:
    properties:
      access_token:
        $ref: '#/definitions/jwttoken.AppJWTInfo'
      refresh_token:
        $ref: '#/definitions/jwttoken.AppJWTInfo'
    type: object
  jwttoken.AppJWTInfo:
    properties:
      expires_in:
        type: string
      token:
        type: string
    type: object
  requests.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:9999
info:
  contact:
    email: wutong0910@foxmail.com
    name: Away0x
    url: https://github.com/Away0x
  description: goweibo api document
  title: goweibo Api
  version: "1.0"
paths:
  /token/refresh:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/context.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/context.TokenResp'
              type: object
      security:
      - ApiKeyAuth: []
      summary: refresh token
      tags:
      - Token
  /token/store:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录信息
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/requests.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/context.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/context.TokenResp'
              type: object
      summary: create token
      tags:
      - Token
  /user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/context.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/user.User'
                  type: array
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户列表
      tags:
      - User
  /user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户 id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/context.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/user.User'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
